//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public string State { get; set; }
        public Nullable<bool> RecieveNewsLetters { get; set; }
        public string Hobbies { get; set; }
        public Nullable<System.DateTime> DateOfSubscription { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MaritialStatus { get; set; }
        public string Address { get; set; }
        public decimal RegistrationFee { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
